name: CI – PackageCompiler.jl

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'test packagecompiler')"
    runs-on: self-hosted
    strategy:
      matrix:
        arch:
          - x64
        # Add / change Julia versions here
        julia-version:
          - '1.11'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}

      - name: Cache Julia packages
        uses: julia-actions/cache@v2

      - name: Install dependencies
        working-directory: pkgcompiler
        run: |
          julia --project -e 'using Pkg; Pkg.instantiate()'

      - name: Run PackageCompiler
        working-directory: pkgcompiler
        run: |
          julia --project build.jl
